services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: webapp_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dandan1234
      MYSQL_DATABASE: blogdb
      MYSQL_USER: webapp
      MYSQL_PASSWORD: webapp123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webapp_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Go Web Application
  webapp:
    build: .
    container_name: webapp_go
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=webapp
      - DB_PASSWORD=webapp123
      - DB_NAME=blogdb
    volumes:
      - ./logs:/root/logs
      - ./static:/root/static
      - ./templates:/root/templates
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - webapp_network

volumes:
  mysql_data:

networks:
  webapp_network:
    driver: bridge
